USE sakila;

-- 1. List the number of films per category.

SELECT COUNT(film_id) AS Number_of_films, rating FROM sakila.film
GROUP BY rating;

-- 2. Retrieve the store ID, city, and country for each store.
SELECT s.store_id, c.city, co.country FROM sakila.store AS s
JOIN sakila.address AS a
ON s.address_id = a.address_id
JOIN sakila.city AS c
ON a.city_id = c.city_id
JOIN sakila.country as co
ON c.country_id = co.country_id;

-- 3. Calculate the total revenue generated by each store in dollars.
SELECT st.store_id, SUM(p.amount) AS Total_revenue FROM sakila.payment AS p
JOIN sakila.staff AS s
ON p.staff_id = s.staff_id
JOIN sakila.store AS st
ON s.store_id = st.store_id
GROUP BY p.staff_id;

-- 4. Determine the average running time of films for each category
SELECT ca.name, AVG(f.length) AS average_length FROM sakila.film AS f
JOIN sakila.film_category AS c
ON f.film_id = c.film_id
JOIN sakila.category as ca
ON c.category_id = ca.category_id
GROUP BY ca.name;